name: BuyAccruedBlocks
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.BuyAccruedBlocks.Main
depend: [GriefPrevention, Vault]
commands:
   buyclaimblocks:
      description: Purchases additional claim blocks with server money.  Doesn't work on servers without a Vault-compatible economy plugin.
      usage: /BuyClaimBlocks <numberOfBlocks>
      aliases: buyclaim
      permission: griefprevention.buysellclaimblocks